
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

set laststatus=2
set showtabline=2
set noshowmode
set t_Co=256

colorscheme elflord

if has("gui_running")
	set guifont=Terminus\ 10
	set guioptions -=m "hide menu bar
	set guioptions -=T "hide toolbar
	set guioptions -=r "disable scrollbar
endif
